-- MySQL Script generated by MySQL Workbench
-- Fri May 15 14:17:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `area_salud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `area_salud` ;

CREATE TABLE IF NOT EXISTS `area_salud` (
  `idarea_salud` INT NOT NULL,
  `consulta_medica` VARCHAR(30) NOT NULL,
  `chequeo_medica` VARCHAR(30) NOT NULL,
  `actualizacion_medica` VARCHAR(30) NOT NULL,
  `ficha_medica` VARCHAR(30) NOT NULL,
  `psicologia_idpsicologia` INT NOT NULL,
  PRIMARY KEY (`idarea_salud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `encuesta` ;

CREATE TABLE IF NOT EXISTS `encuesta` (
  `idencuesta` INT NOT NULL,
  `tipo_encuesta` VARCHAR(30) NOT NULL,
  `preguntas_salud` VARCHAR(30) NOT NULL,
  `preguntas_emocionales` VARCHAR(30) NOT NULL,
  `balance_de_respuestas` VARCHAR(30) NOT NULL,
  `consejo_post_encuesta` VARCHAR(30) NOT NULL,
  `nueva_consulta` VARCHAR(30) NOT NULL,
  `expediente_profesor_idexpediente_profesor` INT NOT NULL,
  PRIMARY KEY (`idencuesta`, `expediente_profesor_idexpediente_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expediente_profesor_has_trabajo_academico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expediente_profesor_has_trabajo_academico` ;

CREATE TABLE IF NOT EXISTS `expediente_profesor_has_trabajo_academico` (
  `expediente_profesor_idexpediente_profesor` INT NOT NULL,
  `trabajo_academico_idtrabajo_academico` INT NOT NULL,
  PRIMARY KEY (`expediente_profesor_idexpediente_profesor`, `trabajo_academico_idtrabajo_academico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `login` ;

CREATE TABLE IF NOT EXISTS `login` (
  `idlogin` INT NOT NULL,
  `correo_institucional` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(30) NOT NULL,
  `solicitar_registro` VARCHAR(30) NOT NULL,
  `recuperar` VARCHAR(30) NOT NULL,
  `expediente_profesor_idexpediente_profesor` INT NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materias` ;

CREATE TABLE IF NOT EXISTS `materias` (
  `idmaterias` INT NOT NULL,
  `materia_nombre` VARCHAR(30) NOT NULL,
  `dia` VARCHAR(30) NOT NULL,
  `hora` DATETIME NOT NULL,
  `accion` VARCHAR(30) NOT NULL,
  `trabajo_academico_idtrabajo_academico` INT NOT NULL,
  `trabajo_academico_nivel_carga_academica_idnivel_carga_academica` INT NOT NULL,
  PRIMARY KEY (`idmaterias`, `trabajo_academico_idtrabajo_academico`, `trabajo_academico_nivel_carga_academica_idnivel_carga_academica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivel_carga_academica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nivel_carga_academica` ;

CREATE TABLE IF NOT EXISTS `nivel_carga_academica` (
  `idnivel_carga_academica` INT NOT NULL,
  `materias_x_profesor` VARCHAR(30) NOT NULL,
  `semestres_x_profesor` VARCHAR(30) NOT NULL,
  `bienestar_profesor` VARCHAR(30) NOT NULL,
  `profesores_disponibles` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idnivel_carga_academica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perfil_profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perfil_profesor` ;

CREATE TABLE IF NOT EXISTS `perfil_profesor` (
  `idperfil_profesor` INT NOT NULL,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  `especialidad` VARCHAR(30) NOT NULL,
  `biografia_profesional` VARCHAR(30) NOT NULL,
  `area_salud_idarea_salud` INT NOT NULL,
  PRIMARY KEY (`idperfil_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psicologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psicologia` ;

CREATE TABLE IF NOT EXISTS `psicologia` (
  `idpsicologia` INT NOT NULL,
  `test` VARCHAR(30) NOT NULL,
  `evaluacion_psicologica` VARCHAR(30) NOT NULL,
  `consejos_psicologicos` VARCHAR(30) NOT NULL,
  `carga_academica` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idpsicologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabajo_academico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabajo_academico` ;

CREATE TABLE IF NOT EXISTS `trabajo_academico` (
  `idtrabajo_academico` INT NOT NULL,
  `materia_asignadas` VARCHAR(30) NOT NULL,
  `control_calificaciones` VARCHAR(30) NOT NULL,
  `corte_notas_semestre` VARCHAR(30) NOT NULL,
  `bitacora` VARCHAR(30) NOT NULL,
  `resumen_academico` VARCHAR(30) NOT NULL,
  `nivel_carga_academica_idnivel_carga_academica` INT NOT NULL,
  PRIMARY KEY (`idtrabajo_academico`, `nivel_carga_academica_idnivel_carga_academica`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
